---
# https://grafana.com/docs/agent/latest/configuration/create-config-file/
# https://stackoverflow.com/questions/49829423/prometheus-add-target-specific-label-in-static-configs
# https://github.com/prometheus/blackbox_exporter#prometheus-configuration
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
# https://github.com/grafana/agent/blob/main/example/docker-compose/agent/config/agent.yaml

server:
  log_level: debug
      
metrics:
  global:
    scrape_interval: 60s
    external_labels:
      cluster: prod
      namespace: heroku
      container: grafana-agent
      pod: grafana-agent-01
    remote_write:
        - url: https://prometheus-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 747939
            password: eyJrIjoiODY5YmJlZjM1YThhMDMzZjAxZjA4NGJkZjA0ZjI1NzViMjhiOWI1ZSIsIm4iOiJLZXkxIiwiaWQiOjc4Mzc4N30=  
        
  configs:
    - name: agent
      scrape_configs:
        - job_name: grafana-agent
          static_configs:
            - targets: 
                - '127.0.0.1:${PORT}'
              labels:
                env: 'prod'
    